### PR TITLE
Jkwok678/change start screen

### PR DESCRIPTION
**Pull request by jkwok678**
Buttons are disabled unless ros_loc is set.

### CODE REVIEW

**Comment by zarethrex** [comment]
I do not understand why you would want to start the application without setting ROS, it does not make any sense to me

**Comment by jkwok678** [comment]
I was thinking about the user workflow. I thought it felt a little odd when you are greeted by a File Manager as soon as you open the application. You don't really see other applications that just show you a File Manager as soon as you start it.

**Comment by zarethrex** [comment]
it is not uncommon for applications to have a setup stage before starting

**Comment by jkwok678** [comment]
What do you think of a wizard or something similar to explain to people what's happening, if they don't read the readme.

**Pull request closed without merging**
